use baml_types::ir_type::TypeGeneric;
use dir_writer::{FileCollector, GeneratorArgs, IntermediateRepr, LanguageFeatures};
use functions::{render_functions, render_functions_parse, render_functions_stream, render_runtime_code, render_source_files, render_type_map};
use generated_types::{render_kotlin_stream_types, render_kotlin_types};
use internal_baml_core::ir::TypeValue;

mod functions;
mod generated_types;
mod ir_to_kotlin;
mod package;
mod test_macros;
mod r#type;
mod utils;

#[derive(Default)]
pub struct KotlinLanguageFeatures;

impl LanguageFeatures for KotlinLanguageFeatures {
    const CONTENT_PREFIX: &'static str = r#"
// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, add the BAML Kotlin SDK
//  dependency to your project.
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
        "#;

    fn name() -> &'static str {
        "kotlin"
    }

    fn generate_sdk_files(
        &self,
        collector: &mut FileCollector<Self>,
        ir: std::sync::Arc<IntermediateRepr>,
        args: &GeneratorArgs,
    ) -> Result<(), anyhow::Error> {
        let pkg = package::CurrentRenderPackage::new("baml_client", ir.clone());
        let file_map = args.file_map_as_json_string()?;

        // Source map
        collector.add_file("BamlSourceMap.kt", render_source_files(file_map)?)?;

        // Runtime initialization
        collector.add_file("BamlRuntimeInit.kt", render_runtime_code(&pkg)?)?;

        // Functions
        let functions = ir
            .functions
            .iter()
            .map(|f| ir_to_kotlin::functions::ir_function_to_kotlin(f, &pkg))
            .collect::<Vec<_>>();
        collector.add_file("BamlFunctions.kt", render_functions(&functions, &pkg)?)?;
        collector.add_file(
            "BamlStreamFunctions.kt",
            render_functions_stream(&functions, &pkg)?,
        )?;
        collector.add_file(
            "BamlParseFunctions.kt",
            render_functions_parse(&functions, &pkg)?,
        )?;

        // Classes
        let kotlin_classes = ir
            .walk_classes()
            .map(|c| ir_to_kotlin::classes::ir_class_to_kotlin(c.item, &pkg))
            .collect::<Vec<_>>();

        // Enums
        let enums = ir
            .walk_enums()
            .map(|e| ir_to_kotlin::enums::ir_enum_to_kotlin(e.item, &pkg))
            .collect::<Vec<_>>();

        // Unions
        let unions = {
            let mut unions = ir
                .walk_all_non_streaming_unions()
                .flat_map(|t| ir_to_kotlin::unions::ir_union_to_kotlin(&t, &pkg))
                .collect::<Vec<_>>();
            unions.sort_by_key(|u| u.name.clone());
            unions.dedup_by_key(|u| u.name.clone());
            unions
        };

        // Type aliases
        let type_aliases = ir.walk_type_aliases().collect::<Vec<_>>();

        let invalid_cycles = ir
            .structural_recursive_alias_cycles()
            .iter()
            .filter(|&cycle| {
                cycle.iter().all(|(_, field_type)| {
                    field_type
                        .find_if(
                            &|t| match t {
                                TypeGeneric::Class { .. } => true,
                                TypeGeneric::Enum { .. } => true,
                                TypeGeneric::Literal(..) => true,
                                TypeGeneric::Primitive(TypeValue::Null, ..) => false,
                                TypeGeneric::Primitive(..) => true,
                                _ => false,
                            },
                            true,
                        )
                        .is_empty()
                })
            })
            .flat_map(|cycle| {
                let keys = cycle.keys().cloned().collect::<Vec<_>>();
                let first_key = keys[0].clone();
                keys.into_iter().map(move |k| (k, first_key.clone()))
            })
            .collect::<baml_types::BamlMap<_, _>>();

        let mut kotlin_type_aliases = type_aliases
            .iter()
            .map(|c| {
                ir_to_kotlin::type_aliases::ir_type_alias_to_kotlin(
                    c.item,
                    &pkg,
                    invalid_cycles.get(&c.elem().name),
                )
            })
            .collect::<Vec<_>>();
        kotlin_type_aliases.sort_by(|a, b| a.name.cmp(&b.name));

        // Stream unions
        let stream_unions = {
            let mut unions = ir
                .walk_all_streaming_unions()
                .flat_map(|t| ir_to_kotlin::unions::ir_union_to_kotlin_stream(&t, &pkg))
                .collect::<Vec<_>>();
            unions.sort_by_key(|u| u.name.clone());
            unions.dedup_by_key(|u| u.name.clone());
            unions
        };

        // Type map
        collector.add_file(
            "BamlTypeMap.kt",
            render_type_map(&kotlin_classes, &enums, &unions, &stream_unions, &pkg)?,
        )?;

        // Types package
        pkg.set("baml_client.types");
        collector.add_file(
            "types/Classes.kt",
            render_kotlin_types(&kotlin_classes, &pkg)?,
        )?;
        collector.add_file("types/Enums.kt", render_kotlin_types(&enums, &pkg)?)?;
        collector.add_file("types/Unions.kt", render_kotlin_types(&unions, &pkg)?)?;
        collector.add_file(
            "types/TypeAliases.kt",
            render_kotlin_types(&kotlin_type_aliases, &pkg)?,
        )?;

        // Stream types package
        let stream_classes = ir
            .walk_classes()
            .map(|c| ir_to_kotlin::classes::ir_class_to_kotlin_stream(c.item, &pkg))
            .collect::<Vec<_>>();

        let mut stream_type_aliases = type_aliases
            .iter()
            .map(|c| {
                ir_to_kotlin::type_aliases::ir_type_alias_to_kotlin_stream(
                    c.item,
                    &pkg,
                    invalid_cycles.get(&c.elem().name),
                )
            })
            .collect::<Vec<_>>();
        stream_type_aliases.sort_by(|a, b| a.name.cmp(&b.name));

        pkg.set("baml_client.stream_types");
        collector.add_file(
            "stream_types/Classes.kt",
            render_kotlin_stream_types(&stream_classes, &pkg)?,
        )?;
        collector.add_file(
            "stream_types/Unions.kt",
            render_kotlin_stream_types(&stream_unions, &pkg)?,
        )?;
        collector.add_file(
            "stream_types/TypeAliases.kt",
            render_kotlin_stream_types(&stream_type_aliases, &pkg)?,
        )?;

        Ok(())
    }
}

// TODO: Add test-harness integration tests once baml_cffi build.rs
// doesn't require protoc-gen-go. For now, unit tests in ir_to_kotlin/ cover
// the type conversion logic.
//
// #[cfg(test)]
// mod kotlin_tests {
//     use test_harness::{create_code_gen_test_suites, TestLanguageFeatures};
//     impl TestLanguageFeatures for crate::KotlinLanguageFeatures {
//         fn test_name() -> &'static str { "kotlin" }
//     }
//     create_code_gen_test_suites!(crate::KotlinLanguageFeatures);
// }

#[cfg(test)]
mod tests {
    #[test]
    fn test_name() {
        use std::str::FromStr;

        use dir_writer::LanguageFeatures;

        let gen_type =
            baml_types::GeneratorOutputType::from_str(crate::KotlinLanguageFeatures::name())
                .expect("KotlinLanguageFeatures name should be a valid GeneratorOutputType");
        assert_eq!(gen_type, baml_types::GeneratorOutputType::Kotlin);
    }
}

#[cfg(test)]
mod render_tests {
    use internal_baml_core::ir::repr::make_test_ir;

    use crate::{
        functions::{render_functions, render_functions_parse, render_functions_stream, render_type_map},
        generated_types::{render_kotlin_stream_types, render_kotlin_types},
        ir_to_kotlin::{classes, enums, functions as fn_conv, type_aliases, unions},
        package::CurrentRenderPackage,
    };

    /// Helper: build IR, convert to Kotlin types, render templates, return all generated files.
    fn render_all(baml: &str) -> Vec<(String, String)> {
        let ir = make_test_ir(baml).expect("Valid BAML");
        let ir = std::sync::Arc::new(ir);
        let pkg = CurrentRenderPackage::new("baml_client", ir.clone());

        let mut files = Vec::new();

        // Functions
        let functions: Vec<_> = ir
            .functions
            .iter()
            .map(|f| fn_conv::ir_function_to_kotlin(f, &pkg))
            .collect();
        files.push((
            "BamlFunctions.kt".to_string(),
            render_functions(&functions, &pkg).unwrap(),
        ));
        files.push((
            "BamlStreamFunctions.kt".to_string(),
            render_functions_stream(&functions, &pkg).unwrap(),
        ));
        files.push((
            "BamlParseFunctions.kt".to_string(),
            render_functions_parse(&functions, &pkg).unwrap(),
        ));

        // Classes
        let kotlin_classes: Vec<_> = ir
            .walk_classes()
            .map(|c| classes::ir_class_to_kotlin(c.item, &pkg))
            .collect();

        // Enums
        let kotlin_enums: Vec<_> = ir
            .walk_enums()
            .map(|e| enums::ir_enum_to_kotlin(e.item, &pkg))
            .collect();

        // Unions
        let kotlin_unions: Vec<_> = {
            let mut unions: Vec<_> = ir
                .walk_all_non_streaming_unions()
                .flat_map(|t| unions::ir_union_to_kotlin(&t, &pkg))
                .collect();
            unions.sort_by_key(|u| u.name.clone());
            unions.dedup_by_key(|u| u.name.clone());
            unions
        };

        // Type aliases
        let type_aliases: Vec<_> = ir.walk_type_aliases().collect();
        let mut kotlin_type_aliases: Vec<_> = type_aliases
            .iter()
            .map(|c| type_aliases::ir_type_alias_to_kotlin(c.item, &pkg, None))
            .collect();
        kotlin_type_aliases.sort_by(|a, b| a.name.cmp(&b.name));

        // Stream unions
        let stream_unions: Vec<_> = {
            let mut unions: Vec<_> = ir
                .walk_all_streaming_unions()
                .flat_map(|t| unions::ir_union_to_kotlin_stream(&t, &pkg))
                .collect();
            unions.sort_by_key(|u| u.name.clone());
            unions.dedup_by_key(|u| u.name.clone());
            unions
        };

        // Type map
        files.push((
            "BamlTypeMap.kt".to_string(),
            render_type_map(&kotlin_classes, &kotlin_enums, &kotlin_unions, &stream_unions, &pkg)
                .unwrap(),
        ));

        // Types package
        pkg.set("baml_client.types");
        files.push((
            "types/Classes.kt".to_string(),
            render_kotlin_types(&kotlin_classes, &pkg).unwrap(),
        ));
        files.push((
            "types/Enums.kt".to_string(),
            render_kotlin_types(&kotlin_enums, &pkg).unwrap(),
        ));
        files.push((
            "types/Unions.kt".to_string(),
            render_kotlin_types(&kotlin_unions, &pkg).unwrap(),
        ));
        files.push((
            "types/TypeAliases.kt".to_string(),
            render_kotlin_types(&kotlin_type_aliases, &pkg).unwrap(),
        ));

        // Stream types package
        let stream_classes: Vec<_> = ir
            .walk_classes()
            .map(|c| classes::ir_class_to_kotlin_stream(c.item, &pkg))
            .collect();
        let mut stream_type_aliases: Vec<_> = type_aliases
            .iter()
            .map(|c| type_aliases::ir_type_alias_to_kotlin_stream(c.item, &pkg, None))
            .collect();
        stream_type_aliases.sort_by(|a, b| a.name.cmp(&b.name));

        pkg.set("baml_client.stream_types");
        files.push((
            "stream_types/Classes.kt".to_string(),
            render_kotlin_stream_types(&stream_classes, &pkg).unwrap(),
        ));
        files.push((
            "stream_types/Unions.kt".to_string(),
            render_kotlin_stream_types(&stream_unions, &pkg).unwrap(),
        ));
        files.push((
            "stream_types/TypeAliases.kt".to_string(),
            render_kotlin_stream_types(&stream_type_aliases, &pkg).unwrap(),
        ));

        files
    }

    fn get_file<'a>(files: &'a [(String, String)], name: &str) -> &'a str {
        files
            .iter()
            .find(|(n, _)| n == name)
            .map(|(_, content)| content.as_str())
            .unwrap_or_else(|| panic!("File '{}' not found", name))
    }

    // ==================== BASIC RENDERING ====================

    #[test]
    fn test_render_simple_class() {
        let files = render_all(
            r##"
            class Person {
                name string
                age int
            }
            function Greet(p: Person) -> string {
                client "openai/gpt-4o"
                prompt #"Hello {{ p.name }}"#
            }
            "##,
        );

        let classes = get_file(&files, "types/Classes.kt");
        assert!(classes.contains("data class Person("), "Missing Person class: {}", classes);
        assert!(classes.contains("val name: String"), "Missing name field");
        assert!(classes.contains("val age: Long"), "Missing age field");

        let stream_classes = get_file(&files, "stream_types/Classes.kt");
        assert!(stream_classes.contains("data class Person("), "Missing stream Person");
        assert!(
            stream_classes.contains("val name: String?"),
            "Stream fields should be nullable: {}",
            stream_classes
        );
        assert!(
            stream_classes.contains("val age: Long?"),
            "Stream age should be nullable"
        );
    }

    #[test]
    fn test_render_enum() {
        let files = render_all(
            "enum Color {\n  Red\n  Green\n  Blue\n}",
        );

        let enums = get_file(&files, "types/Enums.kt");
        assert!(enums.contains("enum class Color"), "Missing Color enum: {}", enums);
        assert!(enums.contains("Red(\"Red\")"), "Missing Red value");
        assert!(enums.contains("Green(\"Green\")"), "Missing Green value");
        assert!(enums.contains("Blue(\"Blue\")"), "Missing Blue value");
        assert!(enums.contains("fun fromString("), "Missing fromString");
    }

    #[test]
    fn test_render_dynamic_enum() {
        let files = render_all(
            "enum Category {\n  Tech\n  Science\n  @@dynamic\n}",
        );

        let enums = get_file(&files, "types/Enums.kt");
        assert!(enums.contains("enum class Category"), "Missing Category enum");
        // Dynamic enums return null from fromString instead of throwing
        assert!(
            enums.contains("fun fromString(value: String): Category?"),
            "Dynamic enum should return nullable: {}",
            enums
        );
    }

    #[test]
    fn test_render_function() {
        let files = render_all(
            r##"
            function GetGreeting(name: string) -> string {
                client "openai/gpt-4o"
                prompt #"Say hello to {{ name }}"#
            }
            "##,
        );

        let funcs = get_file(&files, "BamlFunctions.kt");
        assert!(funcs.contains("suspend fun GetGreeting("), "Missing function: {}", funcs);
        assert!(funcs.contains("name: String"), "Missing arg");
        assert!(funcs.contains("): String"), "Missing return type");
        assert!(
            funcs.contains("client.callFunction(\"GetGreeting\""),
            "Missing callFunction"
        );
    }

    #[test]
    fn test_render_stream_function() {
        let files = render_all(
            r##"
            function GetGreeting(name: string) -> string {
                client "openai/gpt-4o"
                prompt #"Say hello to {{ name }}"#
            }
            "##,
        );

        let funcs = get_file(&files, "BamlStreamFunctions.kt");
        assert!(funcs.contains("fun GetGreetingStream("), "Missing stream function: {}", funcs);
        assert!(funcs.contains("Flow<BamlResult>"), "Missing Flow return type");
        assert!(
            funcs.contains("client.streamFunction(\"GetGreeting\""),
            "Missing streamFunction"
        );
    }

    // ==================== COMPLEX TYPES ====================

    #[test]
    fn test_render_class_with_containers() {
        let files = render_all(
            r##"
            class Config {
                tags string[]
                metadata map<string, string>
                scores int[]?
            }
            function GetConfig(id: string) -> Config {
                client "openai/gpt-4o"
                prompt #"Config for {{ id }}"#
            }
            "##,
        );

        let classes = get_file(&files, "types/Classes.kt");
        assert!(classes.contains("val tags: List<String>"), "Missing tags: {}", classes);
        assert!(
            classes.contains("val metadata: Map<String, String>"),
            "Missing metadata"
        );
        assert!(classes.contains("val scores: List<Long>?"), "Missing optional scores");
    }

    #[test]
    fn test_render_class_with_nested_class() {
        let files = render_all(
            r##"
            class Address {
                city string
                zip string
            }
            class Person {
                name string
                address Address
            }
            function Extract(text: string) -> Person {
                client "openai/gpt-4o"
                prompt #"Extract: {{ text }}"#
            }
            "##,
        );

        let classes = get_file(&files, "types/Classes.kt");
        assert!(classes.contains("data class Address("), "Missing Address");
        assert!(classes.contains("data class Person("), "Missing Person");
        assert!(classes.contains("val address: Address"), "Missing address field");

        let funcs = get_file(&files, "BamlFunctions.kt");
        // From baml_client package, fully-qualified cross-package reference
        assert!(funcs.contains("): baml_client.types.Person"), "Function should return baml_client.types.Person: {}", funcs);
    }

    #[test]
    fn test_render_union_type() {
        let files = render_all(
            r##"
            class T {
                f int | string
            }
            function Get(x: string) -> T {
                client "openai/gpt-4o"
                prompt #"{{ x }}"#
            }
            "##,
        );

        let unions = get_file(&files, "types/Unions.kt");
        assert!(
            unions.contains("sealed class Union2IntOrString"),
            "Missing union: {}",
            unions
        );
    }

    #[test]
    fn test_render_dynamic_class() {
        let files = render_all(
            r##"
            class DynClass {
                name string
                @@dynamic
            }
            function Get(x: string) -> DynClass {
                client "openai/gpt-4o"
                prompt #"{{ x }}"#
            }
            "##,
        );

        let classes = get_file(&files, "types/Classes.kt");
        assert!(
            classes.contains("dynamicProperties"),
            "Dynamic class should have dynamicProperties: {}",
            classes
        );
    }

    // ==================== TYPE ALIASES ====================

    #[test]
    fn test_render_type_alias() {
        let files = render_all(
            r##"
            type Names = string[]
            class T {
                names Names
            }
            function Get(x: string) -> T {
                client "openai/gpt-4o"
                prompt #"{{ x }}"#
            }
            "##,
        );

        let aliases = get_file(&files, "types/TypeAliases.kt");
        assert!(
            aliases.contains("typealias Names"),
            "Missing type alias: {}",
            aliases
        );
    }

    // ==================== TYPE MAP ====================

    #[test]
    fn test_render_type_map() {
        let files = render_all(
            r##"
            enum Color {
                Red
                Green
                Blue
            }
            class Person {
                name string
                color Color
            }
            function Get(x: string) -> Person {
                client "openai/gpt-4o"
                prompt #"{{ x }}"#
            }
            "##,
        );

        let type_map = get_file(&files, "BamlTypeMap.kt");
        assert!(
            type_map.contains("registerBamlTypes"),
            "Missing registerBamlTypes: {}",
            type_map
        );
        assert!(
            type_map.contains("\"TYPES\", \"Person\""),
            "Missing Person type registration: {}",
            type_map
        );
        assert!(
            type_map.contains("\"TYPES\", \"Color\""),
            "Missing Color type registration: {}",
            type_map
        );
        assert!(
            type_map.contains("\"STREAM_TYPES\", \"Person\""),
            "Missing stream Person registration: {}",
            type_map
        );
    }

    // ==================== MULTI-ARG FUNCTIONS ====================

    #[test]
    fn test_render_multi_arg_function() {
        let files = render_all(
            r##"
            function Translate(text: string, target: string, count: int) -> string {
                client "openai/gpt-4o"
                prompt #"Translate {{ text }} to {{ target }}"#
            }
            "##,
        );

        let funcs = get_file(&files, "BamlFunctions.kt");
        assert!(
            funcs.contains("text: String, target: String, count: Long"),
            "Missing multi-arg signature: {}",
            funcs
        );
    }

    // ==================== ENUM + CLASS COMBO ====================

    #[test]
    fn test_render_enum_return_function() {
        let files = render_all(
            r##"
            enum Sentiment {
                POSITIVE
                NEGATIVE
                NEUTRAL
            }
            function ClassifySentiment(text: string) -> Sentiment {
                client "openai/gpt-4o"
                prompt #"Classify: {{ text }}"#
            }
            "##,
        );

        let funcs = get_file(&files, "BamlFunctions.kt");
        assert!(
            funcs.contains("): baml_client.types.Sentiment"),
            "Function should return baml_client.types.Sentiment: {}",
            funcs
        );

        let enums = get_file(&files, "types/Enums.kt");
        assert!(enums.contains("POSITIVE(\"POSITIVE\")"));
        assert!(enums.contains("NEGATIVE(\"NEGATIVE\")"));
        assert!(enums.contains("NEUTRAL(\"NEUTRAL\")"));
    }

    // ==================== MEDIA TYPES ====================

    #[test]
    fn test_render_class_with_image() {
        let files = render_all(
            r##"
            class T {
                photo image
                doc image?
            }
            function Describe(t: T) -> string {
                client "openai/gpt-4o"
                prompt #"Describe {{ t.photo }}"#
            }
            "##,
        );

        let classes = get_file(&files, "types/Classes.kt");
        assert!(classes.contains("val photo: Image"), "Missing image field: {}", classes);
        assert!(classes.contains("val doc: Image?"), "Missing optional image field");

        // Stream types should get fully-qualified prefix for media
        let stream = get_file(&files, "stream_types/Classes.kt");
        assert!(
            stream.contains("baml_client.types.Image?"),
            "Streaming image should have baml_client.types. prefix: {}",
            stream
        );
    }

    // ==================== DOCSTRINGS ====================

    #[test]
    fn test_render_class_with_docstring() {
        let files = render_all(
            r##"
            /// A person record
            class Person {
                /// The person's full name
                name string
                age int
            }
            function Get(x: string) -> Person {
                client "openai/gpt-4o"
                prompt #"{{ x }}"#
            }
            "##,
        );

        let classes = get_file(&files, "types/Classes.kt");
        assert!(
            classes.contains("A person record"),
            "Missing class docstring: {}",
            classes
        );
        // Field docstrings may or may not be included depending on template
    }

    // ==================== ALL GENERATED FILES PRESENT ====================

    /// Generate fixture files for the Kotlin SDK codegen tests.
    /// Run with: cargo test -p generators-kotlin -- write_codegen_fixture --nocapture --ignored
    #[test]
    #[ignore]
    fn write_codegen_fixture() {
        let baml = r##"
            class Person {
                name string
                age int
                email string?
            }

            class Address {
                street string
                city string
                zip string
            }

            enum Sentiment {
                POSITIVE
                NEGATIVE
                NEUTRAL
            }

            class Receipt {
                store string
                items string[]
                total float
            }

            class SearchResult {
                query string
                result int | string
            }

            function ExtractPerson(input: string) -> Person {
                client "openai/gpt-4o"
                prompt #"Extract person from: {{ input }}"#
            }

            function ClassifySentiment(text: string) -> Sentiment {
                client "openai/gpt-4o"
                prompt #"Classify: {{ text }}"#
            }

            function ExtractReceipt(text: string) -> Receipt {
                client "openai/gpt-4o"
                prompt #"Extract receipt: {{ text }}"#
            }

            function Greet(name: string, greeting: string) -> string {
                client "openai/gpt-4o"
                prompt #"{{ greeting }} {{ name }}"#
            }

            function Search(query: string) -> SearchResult {
                client "openai/gpt-4o"
                prompt #"Search: {{ query }}"#
            }
        "##;

        let files = render_all(baml);

        // Write to a well-known output directory
        let out_dir = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .unwrap()
            .parent()
            .unwrap()
            .parent()
            .unwrap()
            .join("language_client_kotlin/src/test/kotlin/com/boundaryml/baml/codegen/generated");

        std::fs::create_dir_all(&out_dir).unwrap();
        std::fs::create_dir_all(out_dir.join("types")).unwrap();
        std::fs::create_dir_all(out_dir.join("stream_types")).unwrap();

        // Skip function files — they reference a `client` that requires a runtime context.
        // We only need types/enums/unions for codegen compilation tests.
        let skip = ["BamlFunctions.kt", "BamlStreamFunctions.kt", "BamlParseFunctions.kt"];
        for (name, content) in &files {
            if skip.iter().any(|s| name.ends_with(s)) {
                continue;
            }
            let path = out_dir.join(name);
            std::fs::write(&path, content).unwrap();
            println!("Wrote: {}", path.display());
        }

        println!("\nGenerated {} files to {}", files.len(), out_dir.display());
    }

    #[test]
    fn test_all_files_generated() {
        let files = render_all(
            r##"
            enum Status {
                Active
                Inactive
            }
            class Item {
                name string
                status Status
            }
            type Items = Item[]
            function GetItems(q: string) -> Items {
                client "openai/gpt-4o"
                prompt #"{{ q }}"#
            }
            "##,
        );

        let file_names: Vec<&str> = files.iter().map(|(n, _)| n.as_str()).collect();
        let expected = vec![
            "BamlFunctions.kt",
            "BamlStreamFunctions.kt",
            "BamlParseFunctions.kt",
            "BamlTypeMap.kt",
            "types/Classes.kt",
            "types/Enums.kt",
            "types/Unions.kt",
            "types/TypeAliases.kt",
            "stream_types/Classes.kt",
            "stream_types/Unions.kt",
            "stream_types/TypeAliases.kt",
        ];
        for name in &expected {
            assert!(
                file_names.contains(name),
                "Missing file: {}. Got: {:?}",
                name,
                file_names
            );
        }
    }
}
